goldmark:
  tableOfContents:
    startLevel: 2
    endLevel: 4
  
  renderer:
    unsafe: true
  
  extensions:
    passthrough:
      enable: true  
      delimiters:
        block:
          - ["\\[", "\\]"]
          - ["$$", "$$"]
        inline:
          - ["\\(", "\\)"]
          - ["$", "$"]
          

highlight:
  noClasses: false         
  lineNos: true
  lineNumbersInTable: false
  tabWidth: 2

