goldmark:
  renderer:
    unsafe: true
  extensions:
    passthrough:
      enable: true  
      delimiters:
        block:
          - ["\\[", "\\]"]
          - ["$$", "$$"]
        inline:
          - ["\\(", "\\)"]
          - ["$", "$"]
          

highlight:
  noClasses: false         
  lineNos: true
  lineNumbersInTable: false
  tabWidth: 2