author:
  name: "Siddharth Nair"
  bio: Theoretical computer science graduate passionate about computer graphics, mathematical physics, and applying type theory to pure mathematics. 
  email: "ambiverb@gmail.com"
  location: "Nottingham, UK"
  phone: 07387653642
  age: 32

nasaAPIKey: bTx14MEfbGeKqykg9Cn758pm5CQHEY2sNZ47J9Fi